### ISSUE TITLE
error for googlenet_train.py

### ISSUE THREAD

**Issue by fanaiwei** [linwest/SemantIC#2]
when I run googlenet_train.py,when it comes to Epoch 0 batch 781,the result is
Epoch 0 batch 780
Epoch 0 batch 781
Traceback (most recent call last):
  File "D:\论文\语义通信github\SemantIC Semantic Interference Cancellation Towards 6G Wireless Communications\SemantIC-main\googlenet_train.py", line 235, in <module>
    train(net, train_data, test_data, 20, optimizer, criterion)
  File "D:\论文\语义通信github\SemantIC Semantic Interference Cancellation Towards 6G Wireless Communications\SemantIC-main\googlenet_train.py", line 212, in train
    im = Variable(im, require_grad=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'require_grad' is an invalid keyword argument for this function

**Comment by waaanp** [comment]
> 当我运行googlenet_train.py时，当涉及到 Epoch 0 batch 781 时，结果是 Epoch 0 batch 780 Epoch 0 batch 781 Traceback（最近一次调用最后）：文件“D：\论文\语义通信github\SemantIC Semantic Interference Cancellation Towards 6G Wireless Communications\SemantIC-main\googlenet_train.py”，第 235 行，in train（net， train_data，test_data， 20， optimizer， criterion） 文件“D：\论文\语义通信github\SemantIC Semantic Interference Cancellation Towards 6G Wireless Communications\SemantIC-main\googlenet_train.py”，第 212 行，in train im = Variable（im， require_grad=True） ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError： 'require_grad' 是此函数的无效关键字参数

这好像是换个函数的事，请问你最后跑完了吗，我设备跑这个太慢了怀疑下自己配置错误了，cpu和gpu一起跑也很慢
